---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: ark-dev

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: ark-dev
    repo: spritsail/ark-se
    tags:
    - latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push
